scripts/extensions: Avoid 'local' keyword
Don't use the 'local' feature in start script extensions.  It's
supported by (d)ash and various other shells, but not (yet) by POSIX.

diff --git a/scripts/extensions/info b/scripts/extensions/info
--- a/scripts/extensions/info
+++ b/scripts/extensions/info
@@ -1,19 +1,19 @@
 get_info()
 {
-    local response="$(erl_rpc 'eturnal_ctl' 'get_info' || :)"
+    _response="$(erl_rpc 'eturnal_ctl' 'get_info' || :)"
 
-    case $response in
+    case $_response in
         '{ok,'*)
-            echo "$response" | sed -e 's/{ok, *"\(.*\)"}/\1/' -e 's/~n/\
+            echo "$_response" | sed -e 's/{ok, *"\(.*\)"}/\1/' -e 's/~n/\
 /g'
             exit 0
             ;;
         '{error,'*)
-            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
+            echo "$_response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
-            echo "Unknown error: '$response'" >&2
+            echo "Unknown error: '$_response'" >&2
             exit 1
             ;;
     esac
diff --git a/scripts/extensions/loglevel b/scripts/extensions/loglevel
--- a/scripts/extensions/loglevel
+++ b/scripts/extensions/loglevel
@@ -1,18 +1,18 @@
 get_loglevel()
 {
-    local response="$(erl_rpc 'eturnal_ctl' 'get_loglevel' || :)"
+    _response="$(erl_rpc 'eturnal_ctl' 'get_loglevel' || :)"
 
-    case $response in
+    case $_response in
         '{ok,'*)
-            echo "$response" | sed 's/{ok, *"\(.*\)"}/\1/'
+            echo "$_response" | sed 's/{ok, *"\(.*\)"}/\1/'
             exit 0
             ;;
         '{error,'*)
-            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
+            echo "$_response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
-            echo "Unknown error: '$response'" >&2
+            echo "Unknown error: '$_response'" >&2
             exit 1
             ;;
     esac
@@ -20,19 +20,19 @@ get_loglevel()
 
 set_loglevel()
 {
-    local level="$1"
-    local response="$(erl_rpc 'eturnal_ctl' 'set_loglevel' "[$level]" || :)"
+    _level="$1"
+    _response="$(erl_rpc 'eturnal_ctl' 'set_loglevel' "[$_level]" || :)"
 
-    case $response in
+    case $_response in
         'ok')
             exit 0
             ;;
         '{error,'*)
-            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
+            echo "$_response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
-            echo "Unknown error: '$response'" >&2
+            echo "Unknown error: '$_response'" >&2
             exit 1
             ;;
     esac
diff --git a/scripts/extensions/reload b/scripts/extensions/reload
--- a/scripts/extensions/reload
+++ b/scripts/extensions/reload
@@ -1,17 +1,17 @@
 reload()
 {
-    local response="$(erl_rpc 'eturnal_ctl' 'reload' || :)"
+    _response="$(erl_rpc 'eturnal_ctl' 'reload' || :)"
 
-    case $response in
+    case $_response in
         'ok')
             exit 0
             ;;
         '{error,'*)
-            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
+            echo "$_response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
-            echo "Unknown error: '$response'" >&2
+            echo "Unknown error: '$_response'" >&2
             exit 1
             ;;
     esac
diff --git a/scripts/extensions/version b/scripts/extensions/version
--- a/scripts/extensions/version
+++ b/scripts/extensions/version
@@ -1,18 +1,18 @@
 get_version()
 {
-    local response="$(erl_rpc 'eturnal_ctl' 'get_version' || :)"
+    _response="$(erl_rpc 'eturnal_ctl' 'get_version' || :)"
 
-    case $response in
+    case $_response in
         '{ok,'*)
-            echo "$response" | sed 's/{ok, *"\(.*\)"}/\1/'
+            echo "$_response" | sed 's/{ok, *"\(.*\)"}/\1/'
             exit 0
             ;;
         '{error,'*)
-            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
+            echo "$_response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
-            echo "Unknown error: '$response'" >&2
+            echo "Unknown error: '$_response'" >&2
             exit 1
             ;;
     esac
