Add 'credentials' and 'password' commands
Add eturnalctl commands for generating ephemeral TURN credentials,
derived from the (first) configured secret.  The 'password' command
prints the password for a given user name, the 'credentials' command
prints the user name and password for a given expiry period (24 hours by
default), optionally with a specified user name suffix.

diff --git a/scripts/extensions/loglevel b/scripts/extensions/loglevel
--- a/scripts/extensions/loglevel
+++ b/scripts/extensions/loglevel
@@ -40,9 +40,9 @@ set_loglevel()
 
 if [ $# -ge 1 ] && [ "x$1" = 'xhelp' ]
 then
-    echo "Usage: $REL_NAME loglevel [level]"
-    echo "Get or set the current log level of $REL_NAME."
-    echo "Valid log levels: critical | error | warning | notice | info | debug"
+    echo "Usage: $REL_NAME loglevel [Level]"
+    echo "Get or set the current log Level of $REL_NAME."
+    echo "Valid log Levels: critical | error | warning | notice | info | debug"
     exit 0
 elif [ $# -eq 0 ]
 then
@@ -53,6 +53,6 @@ then
     ping_or_exit
     set_loglevel "$1"
 else
-    echo "Usage: $REL_NAME loglevel [level]" >&2
+    echo "Usage: $REL_NAME loglevel [Level]" >&2
     exit 2
 fi
