scripts/extensions: Simplify error parsing
Call `echo "$e" | sed "$s"`, not `"echo "$(echo "$e" | sed -e "$s")"` to
parse errors returned by eturnal.

diff --git a/scripts/extensions/loglevel b/scripts/extensions/loglevel
--- a/scripts/extensions/loglevel
+++ b/scripts/extensions/loglevel
@@ -4,11 +4,11 @@ get_loglevel()
 
     case $response in
         '{ok,'*)
-            echo "$(echo "$response" | sed -e 's/{ok, *"\(.*\)"}/\1/')"
+            echo "$response" | sed 's/{ok, *"\(.*\)"}/\1/'
             exit 0
             ;;
         '{error,'*)
-            echo "$(echo "$response" | sed -e 's/{error, *"\(.*\)"}/\1/')" >&2
+            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
@@ -28,7 +28,7 @@ set_loglevel()
             exit 0
             ;;
         '{error,'*)
-            echo "$(echo "$response" | sed -e 's/{error, *"\(.*\)"}/\1/')" >&2
+            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
diff --git a/scripts/extensions/reload b/scripts/extensions/reload
--- a/scripts/extensions/reload
+++ b/scripts/extensions/reload
@@ -7,7 +7,7 @@ reload()
             exit 0
             ;;
         '{error,'*)
-            echo "$(echo "$response" | sed -e 's/{error, *"\(.*\)"}/\1/')" >&2
+            echo "$response" | sed 's/{error, *"\(.*\)"}/\1/' >&2
             exit 1
             ;;
         *)
