make-binaries: Check for native OTP installation
Make sure a native Erlang/OTP installation is available for
bootstrapping and running Rebar3.

diff --git a/scripts/make-binaries b/scripts/make-binaries
--- a/scripts/make-binaries
+++ b/scripts/make-binaries
@@ -463,7 +463,9 @@ then
 elif [ $# -eq 0 ]
 then
 	targets="$supported_targets"
+	build_native='true'
 else
+	build_native='false'
 	for target in "$@"
 	do
 		is_supported='false'
@@ -472,6 +474,10 @@ else
 			if [ "$target" = "$supported_target" ]
 			then
 				is_supported='true'
+				if [ "$target" = "$platform" ]
+				then
+					build_native='true'
+				fi
 				break
 			fi
 		done
@@ -485,6 +491,13 @@ else
 		fi
 	done
 	targets="$*"
+fi
+
+if [ "$build_native" = 'false' ] && [ ! -z "${INSTALL_DIR_FOR_OTP:+x}" ]
+then
+	error 'Native Erlang/OTP installation not found.'
+	error "Set INSTALL_DIR_FOR_OTP or add the '$platform' target."
+	exit 1
 fi
 
 if [ "${CHECK_DEPS:-true}" = 'true' ]
